#' Sort feature weights from glmnet models
#'
#' This function sorts feature weights from glmnet models. Input weight object is generated by: predict(glmnet_model, type = 'coefficients', s = lambda).
#' @param glmnet_coef Glmnet model weights object.
#' @return Returns a 3-column data frame: 1) rank based on absolute feature weight, 2) absolute weight, 3) weight sign (positive or negative).
#' @export
#' @examples
#' sort_glmnet_weights(glmnet_coef = glmnet_coef)

sort_glmnet_weights <- function (glmnet_coef){
  nonzero_ind <- which( (!glmnet_coef == 0)[,1] )
  if(length(nonzero_ind) == 1){
    return(NA)
  }else{
    glmnet_coef.weights <- glmnet_coef[ nonzero_ind,  ]
    intercept_ind <- which(names(glmnet_coef.weights) == "(Intercept)")
    glmnet_coef.weights <- glmnet_coef.weights[-intercept_ind]
    pos_weights.names <- labels(which( glmnet_coef.weights > 0))
    neg_weights.names <- labels(which( glmnet_coef.weights < 0))
    glmnet_coef.weights.abs.sort <- sort(abs(glmnet_coef.weights), decreasing = TRUE)

    df.weights <- data.frame(rank = 1:length(glmnet_coef.weights.abs.sort), weight=glmnet_coef.weights.abs.sort, sign=rep(NA, length(glmnet_coef.weights.abs.sort)), row.names = labels(glmnet_coef.weights.abs.sort))
    df.weights[pos_weights.names, "sign"] = "+"
    df.weights[neg_weights.names, "sign"] = "-"
    #fit_coef.weights.order_names <- names(fit_coef.weights.abs)
    return (df.weights)
  }
}
